### ISSUE TITLE
Problem running codon_aln with PAL2NAL

### ISSUE THREAD

**Issue by mbarkdull** [drostlab/orthologr#21]
Hi folks, 

I am having a problem trying to use the function `codon_aln`. I run the command as follows:
```
  Test <- codon_aln(file_aln = system.file('./data/nuc_OG0009506.fasta'), file_nuc = system.file('./data/msa_OG0009506.fasta'), format = "fasta", tool = "pal2nal", get_aln = TRUE)
```

And I get the error:
```
Can't open  at /Library/Frameworks/R.framework/Versions/3.6/Resources/library/orthologr/pal2nal/pal2nal.v14/pal2nal.pl line 365.
[1] "Codon Alignment successfully written in /var/folders/qh/ymwbdpcx1s163pxcmfp7mv5h0000gn/T//RtmpDSOlRf/_alignment/codon_aln/pal2nal.aln."
Error in value[[3L]](cond) : Something went wront with Pal2Nal.pl .
/var/folders/qh/ymwbdpcx1s163pxcmfp7mv5h0000gn/T//RtmpDSOlRf/_alignment/codon_aln/pal2nal.aln could not be read properly.
```
This seems to be the same error message reported in this issue: https://github.com/drostlab/orthologr/issues/5. However, I have been unable to solve it myself. 

I'm using R version 3.6.2 (2019-12-12).

Thank you so much- I really appreciate the work you've done putting this package together!

**Comment by HajkD** [comment]
Hi Megan,

Thank you very much for contacting me.

Is your data path really within the `system.file()` path?

Would it be possible to try the same run without the `system.file()` around your own path?

```r
  Test <- codon_aln(file_aln = './data/nuc_OG0009506.fasta', file_nuc = './data/msa_OG0009506.fasta', format = "fasta", tool = "pal2nal", get_aln = TRUE)
```

The `system.file()` specification is only for the example cases which use example data stored in the `orthologr` package itself. According to the `CRAN policy` of package development, example data should be stored within the package itself and accessed via `system.file()` in the example section of the documentation.

Does this help already? If not, I will start troubleshooting.

Many thanks,
Hajk

**Comment by HajkD** [comment]
P.S. I now also added error messages to the function that will notify you when the input file path doesn't exist. So by re-installing the new `Github` version of `orthologr` these error messages should appear if your `system.file()` path does not exist.

**Comment by mbarkdull** [comment]
This was indeed my problem- thank you so much! I really appreciate the help.

**Comment by HajkD** [comment]
I am glad that I could help :)
