### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by timregan** [drostlab/orthologr#27]
Installation of orthologr keeps failing right at the end. 

I entered:

`if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")`
`BiocManager::install()`
`# Install package dependencies`
`BiocManager::install(c("Biostrings", "GenomicRanges", "GenomicFeatures", "Rsamtools", "rtracklayer"))`
`# install orthologr from GitHub`
`devtools::install_github("HajkD/metablastr")`

Each of these commands worked with no errors or warnings. However, I could not successfully install orthologr using:

`# install orthologr from GitHub`
devtools::install_github("HajkD/orthologr")

Here is the output:

`The downloaded source packages are in
        ‘/tmp/RtmpzBSnhp/downloaded_packages’`
`✔  checking for file ‘/tmp/RtmpzBSnhp/remotes18a86db25059/drostlab-orthologr-c4f4b36/DESCRIPTION’ ...`
`─  preparing ‘orthologr’:`
`✔  checking DESCRIPTION meta-information ...`
`─  cleaning src`
`─  installing the package to process help pages`
`         -----------------------------------`
`─  installing *source* package ‘orthologr’ ...`
`   ** libs`
`   g++ -std=gnu++11 -I"/exports/applications/apps/SL7/R/3.5.3/lib64/R/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -Xclang -fopenmp -I"/exports/eddie/scratch/tregan/R/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o`
`   g++: error: unrecognized command line option ‘-Xclang’`
`   make: *** [RcppExports.o] Error 1`
`   ERROR: compilation failed for package ‘orthologr’`

`─  removing ‘/tmp/RtmpnBxfT7/Rinst2aa561cd54004/orthologr’`
`         -----------------------------------`
`   ERROR: package installation failed`
`Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
  System command error`

 I've tried wiping my R directory, reinstalling BiocManager from the start but it's the same issue each time.
Any ideas what might be wrong?

Many thanks,
Tim

**Comment by HajkD** [comment]
Hi Tim, many thanks for making me aware of this. 

Would it be possible to let me know which operating system you run?

**Comment by ftegenfe** [comment]
Hi, I have the same problem running on the following system:
CentOS Linux release 8.3.2011
Kernel: 4.18.0-147.5.1.el8_1.centos.plus.x86_64
gcc: 8.3.1 20191121
clang: 11.0.0

**Comment by timregan** [comment]
Apologies for the delayed reply. 
I am using Scientific Linux version 7.5 (Nitrogen)
Kernel: Linux 3.10.0-862.14.4.el7.x86_64
gcc: 9.3.0  
clang: 10.0.0

**Comment by ftegenfe** [comment]
Seems to me that the option -Xclang is a clang specific option. However in the output from the install I see

`g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -Xclang -fopenmp -I'/usr/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o`

Where it uses g++ ...

**Comment by timregan** [comment]
I noticed the same, but didn't know how to get around this.. Did you manage to make any progress on it?

**Comment by jos4uke** [comment]
Hi

I also encountered the same error with "-Xclang" not recognized on the g++ command line.
Then I checked the source code for the offending option, and found it in here: https://github.com/drostlab/orthologr/blob/c4f4b36addf851cf3611c866f757779ddb6aaf6c/src/Makevars#L2

I cloned the repo locally and remove the "-Xclang" from Makevars file.
And finally run the installation witout error like this:

```bash
# clone
git clone https://github.com/drostlab/orthologr.git

# edit orthologr/src/Makevars: remove "-Xclang" string on line 2

# run R
R

```

```R
# in R session, install locally with devtools
> devtools::install_local("orthologr/")

"""output
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                               
 2: CRAN packages only                
 3: None                              
 4: colorspace (2.0-1 -> 2.0-2) [CRAN]
 5: cpp11      (0.2.7 -> 0.3.1) [CRAN]
 6: utf8       (1.2.1 -> 1.2.2) [CRAN]
 7: tibble     (3.1.2 -> 3.1.3) [CRAN]
 8: cli        (2.5.0 -> 3.0.1) [CRAN]
 9: isoband    (0.2.4 -> 0.2.5) [CRAN]
10: Rcpp       (1.0.6 -> 1.0.7) [CRAN]
11: stringi    (1.6.2 -> 1.7.3) [CRAN]
12: blob       (1.2.1 -> 1.2.2) [CRAN]
13: ggplot2    (3.3.4 -> 3.3.5) [CRAN]
14: readr      (1.4.0 -> 2.0.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
✔  checking for file ‘/tmp/RtmpBdTpei/filea74a3bbb3f00/orthologr/DESCRIPTION’ (565ms)
─  preparing ‘orthologr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
   Loading required namespace: orthologr
─  saving partial Rd database (2.7s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘orthologr_0.4.0.tar.gz’
   
Installing package into ‘/work/me/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘orthologr’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -fopenmp -I'/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -fopenmp -I'/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gestimator.cpp -o gestimator.o
gcc -I"/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -fopenmp -I'/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c orthologr_init.c -o orthologr_init.o
g++ -std=gnu++11 -shared -L/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/lib -L/usr/local/lib64 -L/usr/lib64/ -o orthologr.so RcppExports.o gestimator.o orthologr_init.o -L/tools/R/R-4.0.4_gcc-9.3.0/lib64/R/lib -lR
installing to /work/me/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-orthologr/00new/orthologr/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (orthologr)

"""
``` 

And then load it

```R
> library(orthologr)

"""output
Le chargement a nécessité le package : data.table
data.table 1.14.0 using 32 threads (see ?getDTthreads).  Latest news: r-datatable.com
"""
```

Hope this will help


FYI
```bash
# uname -a
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# module list
Currently Loaded Modulefiles:
  1) compiler/gcc-9.3.0           2) system/R-4.0.4_gcc-9.3.0     3) compiler/clang-upc-3.9.1-1

```

**Comment by jos4uke** [comment]
I can confirm you that it is no harm removing the "-Xclang" option.
I ran the blast_rec example (https://drostlab.github.io/orthologr/articles/blast.html#the-blast_rec-function), without any error.

```R
> library(orthologr)

"""output
Le chargement a nécessité le package : data.table
data.table 1.14.0 using 32 threads (see ?getDTthreads).  Latest news: r-datatable.com
"""

> blast_rec(query_file   = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
+           subject_file = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'))

"""output
Running blastp: 2.10.1+ ...


Building a new DB, current time: 07/27/2021 00:17:23
New DB name:   /tmp/Rtmp3cRUQV/_blast_db/blastdb_ortho_lyra_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_lyra_cds.fasta_protein.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.0033958 seconds.


Running blastp: 2.10.1+ ...


Building a new DB, current time: 07/27/2021 00:17:25
New DB name:   /tmp/Rtmp3cRUQV/_blast_db/blastdb_ortho_thal_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_thal_cds.fasta_protein.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.00314093 seconds.


# A tibble: 20 x 21
# Groups:   query_id [20]
   query_id  subject_id    perc_identity num_ident_match… alig_length mismatches
   <chr>     <chr>                 <dbl>            <int>       <int>      <int>
 1 AT1G0101… 333554|PACid…          74.0              347         469         80
 2 AT1G0102… 470181|PACid…          91.1              224         246         22
 3 AT1G0103… 470180|PACid…          95.5              343         359         12
 4 AT1G0104… 333551|PACid…          92.0             1812        1970         85
 5 AT1G0105… 909874|PACid…         100                213         213          0
 6 AT1G0106… 470177|PACid…          89.5              580         648         58
 7 AT1G0107… 918864|PACid…          95.1              348         366         14
 8 AT1G0108… 909871|PACid…          90.3              271         300         22
 9 AT1G0109… 470171|PACid…          96.8              420         434          8
10 AT1G0111… 333544|PACid…          93.6              494         528         34
11 AT1G0112… 918858|PACid…          99.2              525         529          4
12 AT1G0114… 470161|PACid…          98.5              446         453          6
13 AT1G0115… 918855|PACid…          72.6              207         285         68
14 AT1G0116… 918854|PACid…          84.9              152         179         19
15 AT1G0117… 311317|PACid…          85.6               83          97          0
16 AT1G0118… 909860|PACid…          92.6              287         310         20
17 AT1G0119… 311315|PACid…          94.2              502         533         30
18 AT1G0120… 470156|PACid…          95.8              228         238         10
19 AT1G0121… 311313|PACid…          95.3              102         107          5
20 AT1G0122… 470155|PACid…          96.7             1021        1056         35
# … with 15 more variables: gap_openings <int>, n_gaps <int>, pos_match <int>,
#   ppos <dbl>, q_start <int>, q_end <int>, q_len <int>, qcov <dbl>,
#   qcovhsp <dbl>, s_start <int>, s_end <int>, s_len <int>, evalue <dbl>,
#   bit_score <dbl>, score_raw <dbl>

"""
```  

FYI

```bash
# uname -a
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# module list
Currently Loaded Modulefiles:
  1) compiler/gcc-9.3.0           2) system/R-4.0.4_gcc-9.3.0     3) compiler/clang-upc-3.9.1-1   4) bioinfo/ncbi-blast-2.10.1+

```

**Comment by HajkD** [comment]
Dear All, 

Thank you very much for all your feedback and help and please accept my apologies for the delayed response.

The reason why I added these [Makevars](https://github.com/drostlab/orthologr/blob/c4f4b36addf851cf3611c866f757779ddb6aaf6c/src/Makevars#L2) lines is because the `data.table` dependencies now requires OpenMP support on Apple machines for multicore processing:

```
Loading required package: data.table
data.table 1.14.0 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
**********
This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
This is a Mac. Please read https://mac.r-project.org/openmp/. Please engage with Apple and ask them for support. Check r-datatable.com for updates, and our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. After several years of many reports of installation problems on Mac, it's time to gingerly point out that there have been no similar problems on Windows or Linux.
**********
```

This was supposedly enabled by adding `-Xclang -fopenmp` and copiling with `clang`.

Since the consensus seems to be that this causes more harm than use, I now removed these lines again,
so that installation should work smoothly again (would it be possible that someone confirms this to me?).

However, I would like to point out that any `data.table` related task may only run in single core mode
on Macs and if someone finds a suitable solution for this, I would be very grateful and happy to include it in the tool (I am also happy to receive pull requests).

Let me know what you think.

Many thanks,
Hajk

**Comment by timregan** [comment]
Thanks so much jos4uke and Hajk - all working fine for me on Linux now.
Best wishes,
Tim
