### ISSUE TITLE
Clarification on pre-processing data and data types for dNdS estimation

### ISSUE THREAD

**Issue by David-Peede** [drostlab/orthologr#30]
Hello Dr. Hajk-Georg Drost! 

For starters thank you for creating this package! It looks incredibly helpful for people who are getting started in phylogenetics—like myself—and I am excited to dive in! Specifically, I am interested in using the `dNdS()` function but have some questions about the best data type to use. 

I have annotated _Drosophila_ assemblies for three closely related taxa from NCBI—here is an example for [D. teissieri](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/746/235/GCF_016746235.2_Prin_Dtei_1.1/). From my reading it seems like I would need to filter the `_protein.faa.gz` file for the longest isoform using the `retrieve_longest_isoforms()` function to avoid potential duplications and subsequent underestimation of the number of 1:1 orthologs—is this correct or does the  `dNdS()` function do this natively? Additionally, if I have annotated assemblies is it better to use a proteome file versus the nucleotide equivalent `_cds_from_genomic.fna.gz` file for the `dNdS()` function? 

Thanks in advance and I look forward to diving into this package this weekend!

-Dave

**Comment by kullrich** [comment]
Dear Dave,

you could e.g. use this function from the CRBHits package [isoform2longest] and go on with orthologr or CRBHits to calculate the dNdS values, as you prefer. However, CRBHits needs to have either NBCI or ENSEMBL input to be able to directly parse the longest isoform from the input data.
see here for an example:
https://mpievolbio-it.pages.gwdg.de/crbhits/articles/V02KaKsVignette.html#isoform
Best regards
Kristian

**Comment by kullrich** [comment]
Dear Dave,
of course, if you need to calculate dNdS you always need to use the coding sequences (CDS) and can not use the protein files. The protein files you normally take to identify first the orthologs and than go on with the dNdS calculations (see e.g. here https://mpievolbio-it.pages.gwdg.de/crbhits/articles/cds2rbh.png and here https://mpievolbio-it.pages.gwdg.de/crbhits/articles/rbh2kaks.png)

**Comment by David-Peede** [comment]
Hi @kullrich thank you very much for your very thoughtful and informative reply! I will look at the CRBHits package for ortholog detection and calculating dNdS! Additionally, your second comment makes a lot of sense to me, however, I am curious about what data type is _**better**_ for the detection of orthologs. Naively I would think the protein files, but I have not thought too deeply about this.

**Comment by kullrich** [comment]
Hi @David-Peede normally protein sequences are used and than these protein alignments are converted back into coding sequence alignments. To my knowledge orthologr is using pal2nal for this conversion, whereas in CRBHits it is only working directly on sequence pairs so far directly in R. orthologr is more rich in the methods how to detect and integrate ortholog detection whereas CRBHits concentrates on conditional-reciprocal best hits. Anyhow, for classical one-to-one relations there might be no problem in either using the one or the other tool, or just use both or in combination with each other.

**Comment by HajkD** [comment]
Dear Dave,

Thank you very much for your kind words and for your excellent question!

Regarding the `retrieve_longest_isoforms()` function: currently it is only intended to select the longest isoform to pass one protein sequence per gene locus into the `orthofinder2()` function. Hence, thus far `dNdS()` doesn't have the `retrieve_longest_isoforms()` function embedded. 

In addition, `dNdS()` takes CDS sequences as input and internally translates them into protein sequences for best reciprocal hit orthology inference and - as @kullrich absolutely correctly stated - passes both CDS and translated protein sequences to `pal2nal` for codon alignment computations.

Did I understand your question (or as it remains now, `feature request`) correctly that it would be useful for your applications to have the option within `dNdS()` to select the longest splice variant from a set of CDS sequences per gene locus and then do all downstream procedures with this longest splice variant?

Your feedback is greatly appreciated!

@kullrich Thank you very much for your excellent comments and suggestions! 

Many thanks,
Hajk

**Comment by David-Peede** [comment]
Hi Hajk,

Thank you for your very thorough response and yes you did answer my question, however, now I have a new one! Say if used the `dNdS()` function with the flag `ortho_detection = "Orthofinder2"` would this lead to potentially spurious results since the input are CDS sequences? Or in this case, would I need to run `retrieve_longest_isoforms()` first?

-Dave

**Comment by HajkD** [comment]
Hi Dave,

I am very glad to hear that I could help. Currently the combination `dNdS(..., ortho_detection = "Orthofinder2")` will unfortunately not work since I didn't have time to implement this feature yet. But once it is available, `retrieve_longest_isoforms()` would either have to be performed before hand or I will embed it internally, so that longest isoform retrieval is done automatically.

I hope this helps?

Best wishes,
Hajk

**Comment by David-Peede** [comment]
Hi Hajk,

That makes perfect sense, thanks for the clarification and all your help!

Very Respectfully, 
Dave
