### ISSUE TITLE
Missing sequences even with  delete_corrupt_cds = FALSE

### ISSUE THREAD

**Issue by ireneortega** [drostlab/orthologr#34]
I have a file with 251 fasta sequences and when I run blast_rec using the 251 sequences as `query_file`, the message printed in the console says:

```
Building a new DB, current time: 08/26/2022 19:18:53
New DB name:   C:\Users\irene\AppData\Local\Temp\RtmpuSmo3J\_blast_db\blastdb_VIRULENCE_GENES_sorted.fasta_protein.fasta
New DB title:  blastdb_VIRULENCE_GENES_sorted.fasta_protein.fasta
Sequence type: Protein
Deleted existing Protein BLAST database named C:\Users\irene\AppData\Local\Temp\RtmpuSmo3J\_blast_db\blastdb_VIRULENCE_GENES_sorted.fasta_protein.fasta
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 245 sequences in 0.0125512 seconds.
```

therefore, only 245 sequences were blasted, what happened to the remaining 6? I am losing information through the process...

**Comment by kullrich** [comment]
Dear Irene,
is it possible that you share the sequence file, since it is just a low number of sequences.
It would be easier to check what happens with the missing ones?

**Comment by ireneortega** [comment]
I found that they contain nucleotides different than A C T G:
>tssB
ATGTCAGATGGATCTTATGCTCCAAAAGAGCGGATTAATATTACATATAAAGCTAAAACTAATGGACAAAATGAGGATGTGGAGTTGCCGTTAAAATTAATGGTAATGGCAAATTTAAAAGGAAAAAACGAAACTCCTTTAGAGGAAAGAGAAATTTTGCAAATTAATAAGATTAATTTTGATCAAGTCATGAGAAAACTCAATATAACAACAAGTTTTAGCGTAAAAAACACTCTTGGAACAGGAGCTGAAGAGCTTGATGTTAAGCTCAATATTGCTAGTATGAAGGATTTTTCTCCAGATAGCTTAGCTAAACAAATACCCGAGCTAAACAAATTATTGCAGCTAAGAGAAGCATTAATGGCTTTAAAAGGYCCTATGGGTAATATTCCTGATTTTAGAAAAGCTGTTTTAGAAGCGTTAAAAAATGAAAAAACTAAAGAAAAATTACTTTTAGAAATTAAACAAGAAGAGCAAGGAAATTAA
>tssC
ATGGCAAATACTAAAGCAGTTGATATGCCAATTATTGAACAAATTATGGAGAAAAGCAAATACTCTAAAACCGATGAAAGTTTTAGTATTGCTAAAAGAGGTGTTGCTGAATTTATTTCAGAAATTGTAAAAAGCGACAATGCTGAAGAAAAAATCAATAAATTTGCACTTGATGAAATGATAGCCCATATTGATTATTTACTCTCAAAACAAATGGATGAAGTTTTACATAATGAAGAATTTCAAAAACTTGAATCTACTTGGCGTGGACTTAGATTTCTAGTTGAAAGAACTGATTTTAATGAAAATATAAAAATTGACCTATTTGATATAAGAAAAGAAGAAGCTTTAGAGGATTTTGAAAACAATCCAGATATAACACAAAGCGTTGTTTATAAAAATATATATTCTTCAGAATATRGACAATTTGGAGGAGAGCCTATAGGAGCAATCATTGGAGATTATCAACTTGGATCAGCAAGTCCTGATATGACTTTTTTAAATAAAATGGCTAGTATTGCGGCTATGAGTCATTCTCCCTTTTTAACATCTTTTGGACCAAAATTTTTTGGGCTTGATGATTATTCTGAACTTGCGAATATTCAAGATTTGCAAGGTTTGCTAGAAGGTCCTCAATATACAAGGTGGAGAACTTTTAGAGAAAATGAAGACTCTAAATATACAGGCTTACTAGTGACAAGATTTTTAGCAAGAAGCCCTTATGATCCTGAAGAAAACCCTATTAAAAGCTTTAACTATAAAGAAAATGTTCATGCTTCGCATAATCATTTATTGTGGGCTAATTCTTCGTATACTTTTTGTACAAGATTAACAGAAAGCTTTGCTAAATATAGATGGTGTGGAAATATTATAGGACCAAAAAGTGGAGGGACTGTTAAGGATCTGCCTACTTATCTTTATGAAAATTTTGGAACTATACAATCAAAAATACCTACAGAAGTTTTGATTACAGATAGGAGAGAGTATGAACTTGCTGAAGCAGGTTTTATAACCTTAACATTAAGAAGAGATAGTAATAATGCAGCATTTTTTTCAGCAAATTCTCCGTTAAAACCAAAATTATTTCAAAATACCCCAGAAGGTAAAGAAGCTGAAACAAATTACAGATTAGGAACTCAACTTCCATATATCTTTTTAATTTCAAGATTGGCGCACTATTTAAAGGTTTTACAACGAGAAGAAATAGGGAGCTGGAAAGAAAGAAGCGATATTGAAAATGGACTTAATGAATGGATTAGACAATATATTTCCGATCAAGAAAATCCACCTTCTGAAGTAAGAAGTCGTCGTCCATTTAGAGCAGCACAAGTGAAAGTTAGTGATATACCAGGAGAGCCAGGATGGTATAAAATAGGGCTAAGTGTCCGACCTCATTTTAAATATATGGGCGGTAATTTTGAACTTTCTTTAGTAGGAAAATTAGATAAAGAATAA
>tssE
ATGTCCTTGCTAGATAAACTGATCCATAATTTAGATGAGCAAAACATTCATATTCCATTCTATCAAAATGATTTTGAGGATGTAAAAAACAATATAAAGGTTTTGCTCAATGCAAAAATTAATGATTGTTATGCTGTAAAAAATTTAGGAATGYCTAATATGGCTGATATTAATCTTAACTCTAATGAATTATGCGTATCAATGGCCAAGGAAATAAGAAAACTAATTGATAACTATGAAAAAAGAATATGTGTAGTTTCTATCACTTATGATAAYAATTTAAGTCCTTGGCAACTTTCTTTTATTGTAAAATGTTTTTTTCAGGATGATCGTTTTAAAGAATTYAATATAGAAATCATCTTTAAAAACAATAGATATTGCGAGGTTAAATGA
>tssF
ATGAAGGATAATATTTTTTATTATCAAAAAGAGCTTGAATATCTATATGAAAAAAGAGAGTATTTTATAAAAAATTATCCAAAGTTAACACCATTTTTGGCATATGATAGCATAGATCCTGATATAGAAAGAATTATTGAAAATTTAGCTAGTTTAAGCTCTAAAATCCATCAAGAGCTTGATGAAAATATACCACACATTGCAGAATCTTTGATTAATATTGTTTCTCCAAATTATACAAATCCTTTACCTTCTTTATGCATGCAAGAATTTAAATTTGAACAAAATAGTAAAGAAAATAACTTAATTATTCCCAAAGGAACTCTTATTAAATCAAAACCAATAGACAAATGTGTTTGTGAATTTAAAACAGTATATGATGTTTATCTTTATTCTATCTCCATCAGCGAAGTTTTTATATCTAGTAAAAATCAAGATTATACTTTCAATTTAACTTTGCAAGTCAATAAGGCAGAAACAAAAATATGTGATTTGGGTTTGGAAAAAATTAATTTATATCTAGGCAATGATACCTATATGTCTAGTACTTTATTATTATACATGCATTCTTATTTAAAAGAATTAAAAATTCAARGTTTAGATACTGATGAAGAATTTTTTCTTAATACCTATAATATKGAAAAAATAGGATTGAATCCAGATGAAAGTAGTTTATCTTATAATGATTTAGGTTTTGAAGCATTTTCCTTACTAAGAGAATATTTTTTCATGCCACATAAATTCAATTTTTTAAGAATCAATGGTTTGGATATTTTAAATAATTGTCAAGGAAAGACAATTAATATTGAATTTAAATTCTCTAAACCATTTCCTGCAAATTGTATTTTTAGAAAAGAATTACTTTCTTTAAGCATGACACCTATTATCAATATCTTTACAAAAAGCGCAGAACCTCTTATAAATAATCACAAAAAAGATAGTTATAGAATTTTTGTGGATAGAAGCCAACCTAAAGCTTACGAAATCATACAGACACTACAGGTTAAAGCACATAATAGTGAAGGCGGCAAAAGGTTATTAAAAAACTATAAAAGTTTTGAACGCTTTGAATTTTTAAAAGATAATCAAAAGGATTTTTATAGCGTAAATACTAAAAAAAATTCCAAAGGAGAGGTATTTAGCGAAATTTCTTTCTTTTCCTCTTATATAATGGATGAAACTATAAGTATTGATCTTTTGTGCTCCAATGGAGATTTACCTTCAAAATTAAAAATAGGTGATATTAATACCTGCGATCTAAAAGGTGTCGATACCAAAAATGTGGAAATTCCAAGCGAAACAAGAAGATGTAGTGTTGATGGTAATTTATTATGGAAGCTTGTTTCTGTGTTATCTTTTTCATATCAAACAATATTGAGCAAAAAAGCTTTTTTTGGTGTGTTGGAAAGCTATAGCTTTTTAGATAATCAATCAAATTGGAAGATTTATAAGCTTTTGCAAGAATCTATAATCGATATTCAAAGTAAAAGCACTTATTTAATAGATGAAAATATCACAAAAAAAGGGACCTTAGCTATTTTTAGTATTAAAGATTCGAAGTTTTACACTTTAGGCGAGGTATATTTATTGGGATTGATTATATCTAAATTTTTAGCTTCTTTTGCTAGTATTAACTCCTTTTGTGAGTTAAAAATAAGATGCCTCGACTCAAAAGAAATTTTACATTACCCTGCTTCTTTTGGAAAAAAAGCTTTAATATGA
>tssJ
ATGTTTTGCAAAAAAAGCTTATTTTTTTTATTGCCAYTATTCTTTTGCGCTTGCTCAAGTGTTGTTAGTGTTAAGATAAATAATGTAGAGAATTCCAATCTTAATAATAGACATGATGATGTTCCTGTTACGGCTATTGTATATCAACTTAAGGATATTAAAAAATTTGAAGAAGCAAGTGATATAGATTTGGCTACTAGAGAAGAGGGGGTGCTAGGCAAGGATAAACTTGATTCTATTAAAACGCAAATTGCACCTAAAGACAATATTATCGCGGTTAAAGTAGATGAAGAAGAGGTTCCTTATGTAGGCATTCTTGTATTATTTGCAAATAATACAAAAAAAACAACAAAAATATGGGCAAAGACCGAAGATGCAAATGGGTTTGGGAAGAATAAGTATTTAAAATTTGAAATATCCAAAGAAGGTATCAAAAGAATTAAATAG
>tssM
ATGTTTAAAAAAATATTTGATTTTGTGAAATCAAGATTATTTATAACTGCTTTTTTGCTTTGTTGTATTTTTCTTTTGAGTATTTTATTTTGGTTTTGGGGTTCTTTAGTAGCTTTTAATGACATATATATTTTTAGTAGTTCATTTTTAAGATTTAGTATTATTTTGATAATTTGGCTTATTGTTTTTTTGTTTTTTTTATTAAAGCCTATTATAAATTTTATATCTTCTTTAAAAAGTGAAAAAAGATTAAAATTTAAAGTCCTAAAAAAAGAAGCTGATGAGTTCACTTACAAATCTAAAAGAAACTTCTTTTTATCTCTTAAAGATGCCAAAGAAACATGGAAGAATGATTTAAAAACAAAAAATTTACCCTTAATTATCATCATAGGAAATGAAGGAGCTGGAAAAAGCACTTTTATTAATTATTCTGACATCGAATACCCACTTAGTGATAGTTTAGAGTCTTATAAAAAATTCCATAAATCTACTAGAAATTTTGCACTTTATGTATCAAAAAAAGGTGCTTTGTTAGATACAGAAGGAAACTATTTTTCACAAGAAGAATTTTTTAAGCCTACAAGTAGCGATGAAATACCCGAAGATGATATAGATAAAAATAGAGATTTTTTAATTAAAAAAAATATATGGAAAAAATTCCTTACTTTTCTCAATAAAAATTTTTTTCATAGCAAACTAAATGGAATTATTTTAGTTGTTGACACTGTAATTTTCTTAAATAATCCTAAGGAGTATTCCAAAAATCTTATTAGATATCTAACAAAAAGAGTAAATGAATGTGAAAAAACTTTAAATTTAAAACTGCCTATTTATATAGTTTTTTCAAAACTCGACTTGATCGAAGGCATGAAAGAGTATTTTGATATTTTCGATAAAAAAATTTCAGATAAAATTTTAGGATTATCTTTTGATAAAATCTTAAGTGAAGAATTTTTAAATAATGAATTTAAAGAATTAAGTGATTCATTATTATGTTCCTTGATGAGTAAAAACTCCCATATTTATAATATAGAAAATAAAAATAAAAGCTACTTATTTTTAAAACAACTTGATAATTTATTTGCATTAGCAAAGACTTTTATTTTGGAAGTGCAAGAAGAAAATAAGCTTAAAAATAATTCTTATCTTAGAGGAGTTTATTTTGTTAGTGCCTATCAAGAAAATATTCCTAGAAATTTCTTACTCGATGCCATATGTGAGAAATATAACTGCAAAAAAGTATTATCAAAATCCAATATTATACATAATAAACAAAGCTATTTTGTTAAATCACTGCTCGAAGATTTAATTTTTACAGATTATTCTTTAAGCACTATGAAATCTTATTCTAAAAAATTATCTTTTTTAATTATAATTTTAATCATAAGCTTTGGAACATATGCTATATCTTCTTATTTTATAAGTAAAAATAATAAAGAATTCGAAAAAAGCCAAAACACCTTAAGATCTTTACAATTGCTTCTTAAAGATCAAGATTATCAAAATTTAAATATTAAACAAAAAGCTGACTTCTTAATTGAATTGAGAAATATTTTAAATACTTATCCTGAACTTTGGCAAGATAATAATATATTTCAATATTTAAATCTAAATCTCTCATACAAAGGATTTAAAGAAGCTAAACAACTTTATTATAAACTGAATGAAGATGTGTTAAAAAATACTTTATTAAAAGAAATGGAATATACTTTACTTACCGATACAAATAAAGAAAATTTAATCAAAACATTATATATGTATAGATCTTTGTTTGAACAAAAATATTTTAATAAAGAAATACTAAAAATTTGGATTAACGAGAATTGGAATACTTTAAGTAAGTATTCAATCTCTAAAGATGACTTTCTAGAAGGGGTGGATGAGCTTAAACAATTTAATCTTAAATCTTTTACAGAAGATGAAAACAGTATACATACAGGAAAAAGAAAACTTGAGAGTATAAGTAGAACTCAAAGAATTTACATTCTTCTTAATTTTTTAAATAGCGATAAACCTAAAGAAAAATATCTTATAAAAGAGGATTTAGGTTTTGCTGCAAATAGTGTATTTTCAAATAACTCTCAAATAACTTCTATAGATAAAATATATACAAAAGTTGGTATGATGGACTTTTTAAATGATTTAAATCAACAAGTTGACACCGCAATCAATATTGAATCTTGGATGCTAGATAACAATTTTAAAGAAAATAAAAACACTTTGACTATGGGTATTTTAAAATTATACTTAAGTGAATACCAAAATGCTTGGCAAAATCTACTCGCTTCATTGCAACCTGTTAGGTATAATACCAAAGAGGCAATGGTTAATGAGCTTAATATCTTATCAAAAAAAGAAAACCCTTTATATTCTTTGTTAAAAATTGTTAGTTCTAATACAAATTTAAATGATGCAGTTTTACTAACTCAAGCCTACAATTTAGGGTTAAATGCTGGGGAAATTAGATCAAATTTTATTGGGGTAAGCAATGCTTTCACACAATATCATAAGCTAGTAAACAAAAATACACTTTTGAGTGTTGGTAATATAGAAGTGGGCAAAGGCACTGATGATGAAAAAATATTAGATATTCTTAATACAAATATTACAAATATGTCCAATAAAATTATAGATTTTAGTTCTAATAATAACCAAAGTGCTGAAGAAAAAATTTCATATGCTCTTGGAGGCAATAAAGATGCCAATGATCCTTTTGCTGTATTTCAAATGAACATAAAAAAATTACCTAATGATTTAGAGAGATATTATAGTCAGCTTTCTAATTATTCGTGGAATTTTATAGAAAATCATGGTATTTCTTTATTTAATACTGCTTGGATTAATGAAGTGTATAATCCATTTGTTAATGATATTGCACCATATTATCCTTTTAATGATGAGAGTGTAGCAGATCTTAGTATGGATAGTTTTAAAACATTTTTTGGAAGAAATGRGACATTAAATAGTTTTTATAAAAAATACTTGAACAATGTTTTAGTAAAAAGAAAAAATAACTATTCTATCAATTCTCAATTTGCTTCAAAATTAAATTTCTCTAAAGAATTTTTAGATTTTATCACCAATGCAGGCAATCTCTCTAGTCTCATACTAAATGGTAATGATAATATAAAAGTTAATTTTACTATTCAAAGCCTTGATTTAAGTGCGGATTTTTCCTTTATAAAGCTTGGCTATGGTAATAAAAATATCCAATATGATCATACTCTTAATCAAACCCTACAAATTGTAGCAGAAAAATTCAATAATGGAACAAGTTTAAATTTTACAGCCTATAACTACTCTAATCCTAATTTAAATTATACAAAATCATATAAAGGGGAATGGGCATGGTATAAGTTTATAAAAGATAATAAAAGTAATTCTATATACAGCATTATATTTAACAATAATAAAAACTTATATTTTGACTTTGAAATTATTAACGGTGCTAGTGAATTAAATAATATAGTTTATATTTTAAACAATCTTAAAATAGTAGAAAATATTACAGGGGTAAATAAACAATGA

and may be the sequences cannot be translated. Would there be the possibility to translate that codons into `?` character?

**Comment by kullrich** [comment]
Hi,
yes would be possible, e.g. with my package MSA2dist:

I have put your sequences in a file with the name 'test.cds.fasta'

```
library(MSA2dist)
library(Biostrings)
cds<-readDNAStringSet("test.cds.fasta")
cds

> cds
DNAStringSet object of length 6:
    width seq                                               names               
[1]   486 ATGTCAGATGGATCTTATGCTCC...AACAAGAAGAGCAAGGAAATTAA tssB
[2]  1455 ATGGCAAATACTAAAGCAGTTGA...TAGGAAAATTAGATAAAGAATAA tssC
[3]   393 ATGTCCTTGCTAGATAAACTGAT...ATAGATATTGCGAGGTTAAATGA tssE
[4]  1722 ATGAAGGATAATATTTTTTATTA...TTGGAAAAAAAGCTTTAATATGA tssF
[5]   447 ATGTTTTGCAAAAAAAGCTTATT...AAGGTATCAAAAGAATTAAATAG tssJ
[6]  3528 ATGTTTAAAAAAATATTTGATTT...TTACAGGGGTAAATAAACAATGA tssM

aa<-MSA2dist::cds2aa(cds)
aa

> aa
AAStringSet object of length 6:
    width seq                                               names               
[1]   162 MSDGSYAPKERINITYKAKTNGQ...ALKNEKTKEKLLLEIKQEEQGN* tssB
[2]   485 MANTKAVDMPIIEQIMEKSKYSK...RPHFKYMGGNFELSLVGKLDKE* tssC
[3]   131 MSLLDKLIHNLDEQNIHIPFYQN...DDRFKEXNIEIIFKNNRYCEVK* tssE
[4]   574 MKDNIFYYQKELEYLYEKREYFI...IRCLDSKEILHYPASFGKKALI* tssF
[5]   149 MFCKKSLFFLLPXFFCACSSVVS...NGFGKNKYLKFEISKEGIKRIK* tssJ
[6]  1176 MFKKIFDFVKSRLFITAFLLCCI...NNIVYILNNLKIVENITGVNKQ* tssM
```

As you will see the codons with IUPAC code are translated into X

```
> alphabetFrequency(aa)
      A  R   N  D  C  Q  E  G H   I   L   K  M  F  P   S  T  W  Y  V U O B J Z
[1,] 10  5  14  7  0  7 17  7 0  10  22  20  7  4  7   7  8  0  2  6 0 0 0 0 0
[2,] 27 26  28 25  2 16 46 28 8  34  42  32  9 28 23  39 24  7 22 17 0 0 0 0 0
[3,]  4  4  17 10  5  4  8  1 2  14  12  12  4  7  2   6  1  1  5  8 0 0 0 0 0
[4,] 15 12  41 31 11 16 41 19 7  56  67  57  7 39 19  58 25  2 31 17 0 0 0 0 0
[5,]  9  3  11 10  3  2 11  6 1  13  11  21  1  9  4   8  7  1  3 13 0 0 0 0 0
[6,] 38 21 139 60  6 33 68 35 8 104 149 123 14 88 18 104 51 14 62 39 0 0 0 0 0
     X * - + . other
[1,] 1 1 0 0 0     0
[2,] 1 1 0 0 0     0
[3,] 3 1 0 0 0     0
[4,] 2 1 0 0 0     0
[5,] 1 1 0 0 0     0
[6,] 1 1 0 0 0     0
```

Best regards

Kristian

**Comment by kullrich** [comment]
Of course the `MSA2dist::cds2aa` function handles not multiple of 3 situations, so if you are sure that your CDS looks fine, you could also just use this easy option from Biostrings:

```
Biostrings::translate(cds, if.fuzzy.codon="X")
```

**Comment by ireneortega** [comment]
Ok, thanks, but how I implement that option into `blast_rec`?

**Comment by kullrich** [comment]
Hi, tyr to 'overwrite' the function `transl` as a quick hack:

original function:

```
transl <- function(sequence){
        return(seqinr::c2s(seqinr::translate(seqinr::s2c(sequence))))
}
```
new function, defined inside your R Console:
```
transl <- function(sequence){
    return(Biostrings::translate(sequence, if.fuzzy.codon="X"))
}
```

**Comment by kullrich** [comment]
OK, problem seem to be the function in R/utils.R:

```
is.dnaSequence <- function(seq){
        return((length(grep("[^(A|C|G|T|a|c|g|t)]", seq)) == 0))
}
```

I have changed it into the following and installed it:

```
is.dnaSequence <- function(seq){
        return((length(grep("[^(A|C|G|T|M|R|W|S|Y|K|V|H|D|B|N|a|c|g|t|m|r|w|s|y|k|v|h|d|b|n)]", seq)) == 0))
}

and now it works.

**Comment by ireneortega** [comment]
Super! It works perfectly now. Thanks a lot @kullrich
