### ISSUE TITLE
unable to install on R4.2

### ISSUE THREAD

**Issue by hannahdevens** [drostlab/orthologr#35]
Hi, I can't install megablastr or orthologr on my version of R (4.2.2). I used devtools::install_github("HajkD/metablastr") and 
devtools::install_github("HajkD/orthologR") and got the following errors:
"Downloading GitHub repo HajkD/metablastr@HEAD
Skipping 17 packages not available: ggridges, ggsci, ggplot2, DBI, RSQLite, rtracklayer, fs, IRanges, readr, stringr, tibble, scales, GenomicRanges, GenomicFeatures, Biostrings, dplyr, seqinr
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T/RtmpVOKJjs/remotes1dc72978a0c/drostlab-metablastr-0c632b4/DESCRIPTION’ (480ms)
─  preparing ‘metablastr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘metablastr_0.3.1.tar.gz’
   
ERROR: dependencies ‘seqinr’, ‘ggridges’ are not available for package ‘metablastr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/metablastr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T//RtmpVOKJjs/file1dc3ae8549a/metablastr_0.3.1.tar.gz’ had non-zero exit status"

"devtools::install_github("HajkD/orthologR")
Downloading GitHub repo HajkD/orthologR@HEAD
Skipping 20 packages not available: Rcpp, Rdpack, scales, ggplot2, ape, readr, tibble, rtracklayer, dtplyr, DBI, IRanges, stringr, RSQLite, Biostrings, foreach, doParallel, dplyr, fs, seqinr, data.table
Downloading GitHub repo HajkD/metablastr@HEAD
Skipping 17 packages not available: ggridges, ggsci, ggplot2, DBI, RSQLite, rtracklayer, fs, IRanges, readr, stringr, tibble, scales, GenomicRanges, GenomicFeatures, Biostrings, dplyr, seqinr
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T/RtmpVOKJjs/remotes1dc42fee7c6/drostlab-metablastr-0c632b4/DESCRIPTION’ (385ms)
─  preparing ‘metablastr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘metablastr_0.3.1.tar.gz’
   
ERROR: dependencies ‘seqinr’, ‘ggridges’ are not available for package ‘metablastr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/metablastr’
Downloading GitHub repo HajkD/metablastr@HEAD
Skipping metablastr, it is already being installed
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T/RtmpVOKJjs/remotes1dc420101fb/drostlab-orthologr-9c1a50e/DESCRIPTION’ ...
─  preparing ‘orthologr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
   Warning: Rd macro package 'Rdpack' is not installed.
   Warning: /private/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T/RtmpuYcI8H/Rbuild81575160d39d/orthologr/man/map_generator_lnc.Rd:120: unknown macro '\insertRef'
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘orthologr_0.4.0.tar.gz’
   
ERROR: dependencies ‘seqinr’, ‘metablastr’, ‘doParallel’, ‘foreach’, ‘Rdpack’ are not available for package ‘orthologr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/orthologr’
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T//RtmpVOKJjs/file1dc6d229a86/metablastr_0.3.1.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/vv/_4lv9dx12j7d3x_j30cs3qdh0000gq/T//RtmpVOKJjs/file1dc764c7b21/orthologr_0.4.0.tar.gz’ had non-zero exit status"

**Comment by HajkD** [comment]
Hi,

> Skipping 17 packages not available: ggridges, ggsci, ggplot2, DBI, RSQLite, rtracklayer, fs, IRanges, readr, stringr, tibble, scales, GenomicRanges, GenomicFeatures, Biostrings, dplyr, seqinr

> ERROR: dependencies ‘seqinr’, ‘ggridges’ are not available for package ‘metablastr’

> ERROR: dependencies ‘seqinr’, ‘metablastr’, ‘doParallel’, ‘foreach’, ‘Rdpack’ are not available for package ‘orthologr’

Installing these dependencies prior to installing `metablastr` and `orthologr` should solve it.

Cheers,
Hajk
