### ISSUE TITLE
Integrate blastx and tblastx options

### ISSUE THREAD

**Issue by qhelleu** [drostlab/orthologr#36]
Hi,
Would it be possible to integrate an option to run blastx and tblastx through orthologr ?
Thanks,
Best.

**Comment by qhelleu** [comment]
I will use metablastr. Sorry for the inconvenience.

**Comment by HajkD** [comment]
Excellent :-) 

I am very happy to hear that you find `orthologr` and `metablastr` useful!

Cheers,
Hajk
