### ISSUE TITLE
Package release request

### ISSUE THREAD

**Issue by gallardoalba** [drostlab/orthologr#43]
would be possible also to provide a [package release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)? It is required for creating the conda package.

Thanks a lot!

**Comment by LotharukpongJS** [comment]
Dear @gallardoalba ,

Thank you for your recommendation! I have now created a release for the current orthologr v0.4.1 (https://github.com/drostlab/orthologr/releases/tag/v0.4.1). I hope this helps :)

Best,
Sodai

**Comment by gallardoalba** [comment]
The draft PR of the conda package; https://github.com/bioconda/bioconda-recipes/pull/42945. Two dependencies are still missing: metablastr and kaks_calculator.

**Comment by gallardoalba** [comment]
Kaks_calculator conda package PR: https://github.com/bioconda/bioconda-recipes/pull/42946

**Comment by kullrich** [comment]
Hi,
kaks_calculator2 is already on biconda:
https://bioconda.github.io/recipes/kakscalculator2/README.html?highlight=kaks_calculator2
Best regards
Kristian
