### ISSUE TITLE
Dependency question

### ISSUE THREAD

**Issue by gallardoalba** [drostlab/orthologr#45]
Hi,
would be technically possible to replace the metablastr dependency by rdiamond? I'm currently working in the orthologr conda recipe.

Best regards.

**Comment by HajkD** [comment]
Hi @gallardoalba 

Yes, absolutely :)

In fact, @LotharukpongJS is working on a solution. Should be there within the next week or so.

If this takes longer, I will implement a prototype version.

I hope this helps?

With very best wishes,
Hajk

**Comment by gallardoalba** [comment]
> Hi @gallardoalba
> 
> Yes, absolutely :)
> 
> In fact, @LotharukpongJS is working on a solution. Should be there within the next week or so.
> 
> If this takes longer, I will implement a prototype version.
> 
> I hope this helps?
> 
> With very best wishes, Hajk

Sure, thanks a lot!

**Comment by HajkD** [comment]
Done! 

@LotharukpongJS kindly implemented the DIAMOND integration which should now work for you (see #46).

I hope this helps!

Cheers,
Hajk

**Comment by gallardoalba** [comment]
> Done!
> 
> @LotharukpongJS kindly implemented the DIAMOND integration which should now work for you (see #46).
> 
> I hope this helps!
> 
> Cheers, Hajk

Thanks a lot!
